project:
  type: website
  output-dir: docs

website: 
  title: "Gapminder Analysis"
  navbar: 
    left:
      - href: index.qmd
        text: "Home"
      - href: life-gdp.qmd
        text: "Life Expectancy and GDP per Capita over Time"
      - href: life-population.qmd
        text: "Life Expectancy and Population"
      - href: specific-country.qmd
        text: "Specific Country Analysis"


format: 
  html:
    theme: sandstone
    css: styles.css

execute: 
  echo: true
